/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package costtrace;

import com.sun.org.apache.xalan.internal.xsltc.runtime.Operators;

/**
 *
 * @author md.rabiulkhan
 */
public class CalculatorS extends javax.swing.JFrame {

    String fNo = "", sNo = "", op = "", res = "";
    
    
    /**
     * Creates new form CalculatorS
     */
    public CalculatorS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField_display = new javax.swing.JTextField();
        jButton_seven = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton_eight = new javax.swing.JButton();
        jButton_nine = new javax.swing.JButton();
        jButton_four = new javax.swing.JButton();
        jButton_five = new javax.swing.JButton();
        jButton_six = new javax.swing.JButton();
        jButton_one = new javax.swing.JButton();
        jButton_two = new javax.swing.JButton();
        jButton_three = new javax.swing.JButton();
        jButton_clear = new javax.swing.JButton();
        jButton_zero = new javax.swing.JButton();
        jButton_equal = new javax.swing.JButton();
        jButton_divide = new javax.swing.JButton();
        jButton_multiply = new javax.swing.JButton();
        jButton_minus = new javax.swing.JButton();
        jButton_plus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField_display.setEditable(false);

        jButton_seven.setText("7");
        jButton_seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_sevenActionPerformed(evt);
            }
        });

        jButton_eight.setText("8");
        jButton_eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eightActionPerformed(evt);
            }
        });

        jButton_nine.setText("9");
        jButton_nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nineActionPerformed(evt);
            }
        });

        jButton_four.setText("4");
        jButton_four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_fourActionPerformed(evt);
            }
        });

        jButton_five.setText("5");
        jButton_five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_fiveActionPerformed(evt);
            }
        });

        jButton_six.setText("6");
        jButton_six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_sixActionPerformed(evt);
            }
        });

        jButton_one.setText("1");
        jButton_one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_oneActionPerformed(evt);
            }
        });

        jButton_two.setText("2");
        jButton_two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_twoActionPerformed(evt);
            }
        });

        jButton_three.setText("3");
        jButton_three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_threeActionPerformed(evt);
            }
        });

        jButton_clear.setText("C");
        jButton_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_clearActionPerformed(evt);
            }
        });

        jButton_zero.setText("0");
        jButton_zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_zeroActionPerformed(evt);
            }
        });

        jButton_equal.setText("=");
        jButton_equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_equalActionPerformed(evt);
            }
        });

        jButton_divide.setText("/");
        jButton_divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_divideActionPerformed(evt);
            }
        });

        jButton_multiply.setText("x");
        jButton_multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_multiplyActionPerformed(evt);
            }
        });

        jButton_minus.setText("-");
        jButton_minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_minusActionPerformed(evt);
            }
        });

        jButton_plus.setText("+");
        jButton_plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_plusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton_seven, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton_eight, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton_nine, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton_divide, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton_four, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton_five, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton_six, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton_multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton_one, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton_two, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton_three, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton_minus, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton_zero, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton_equal, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton_plus, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jTextField_display, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jTextField_display, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_seven, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_eight, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_nine, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_divide, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_four, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_five, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_six, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_one, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_two, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_three, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_minus, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_zero, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_equal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_plus, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sevenActionPerformed
        
        jTextField_display.setText(jTextField_display.getText() + "7");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_sevenActionPerformed

    private void jButton_eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eightActionPerformed
        jTextField_display.setText(jTextField_display.getText() + "8");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_eightActionPerformed

    private void jButton_nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nineActionPerformed
        jTextField_display.setText(jTextField_display.getText() + "9");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_nineActionPerformed

    private void jButton_fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_fourActionPerformed
        jTextField_display.setText(jTextField_display.getText() + "4");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_fourActionPerformed

    private void jButton_fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_fiveActionPerformed
        jTextField_display.setText(jTextField_display.getText() + "5");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_fiveActionPerformed

    private void jButton_sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sixActionPerformed
        jTextField_display.setText(jTextField_display.getText() + "6");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_sixActionPerformed

    private void jButton_oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_oneActionPerformed
        
        jTextField_display.setText(jTextField_display.getText() + "1");
    }//GEN-LAST:event_jButton_oneActionPerformed

    private void jButton_twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_twoActionPerformed
        // TODO add your handling code here:
        jTextField_display.setText(jTextField_display.getText() + "2");
    }//GEN-LAST:event_jButton_twoActionPerformed

    private void jButton_threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_threeActionPerformed
        jTextField_display.setText(jTextField_display.getText() + "3");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_threeActionPerformed

    private void jButton_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_clearActionPerformed
        jTextField_display.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_clearActionPerformed

    private void jButton_plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_plusActionPerformed
        fNo = jTextField_display.getText();
        jTextField_display.setText("");
        op = "+";
    }//GEN-LAST:event_jButton_plusActionPerformed

    public void calculate(String op){
        sNo = jTextField_display.getText();
        
        float sum = 0;
        
        if(op == "+"){
            sum = Float.parseFloat(fNo)+ Float.parseFloat(sNo);
        }
        if(op == "-"){
            sum = Float.parseFloat(fNo)- Float.parseFloat(sNo);
        }
        if(op == "*"){
            sum = Float.parseFloat(fNo)* Float.parseFloat(sNo);
        }
        
        if(op == "/"){
            sum = Float.parseFloat(fNo)/ Float.parseFloat(sNo);
        }
        
        
        jTextField_display.setText(String.valueOf(sum));
        
        fNo="";
        sNo="";
    }
    
    private void jButton_equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_equalActionPerformed
        // TODO add your handling code here:
        calculate(op);
        
        
    }//GEN-LAST:event_jButton_equalActionPerformed

    private void jButton_minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_minusActionPerformed
        // TODO add your handling code here:
        fNo = jTextField_display.getText();
        jTextField_display.setText("");
        op="-";
    }//GEN-LAST:event_jButton_minusActionPerformed

    private void jButton_multiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_multiplyActionPerformed
        // TODO add your handling code here:
        fNo = jTextField_display.getText();
        jTextField_display.setText("");
        op="*";
    }//GEN-LAST:event_jButton_multiplyActionPerformed

    private void jButton_divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_divideActionPerformed
        // TODO add your handling code here:
        fNo = jTextField_display.getText();
        jTextField_display.setText("");
        op="/";
    }//GEN-LAST:event_jButton_divideActionPerformed

    private void jButton_zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_zeroActionPerformed
        // TODO add your handling code here:
        jTextField_display.setText(jTextField_display.getText() + "0"); 
    }//GEN-LAST:event_jButton_zeroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_clear;
    private javax.swing.JButton jButton_divide;
    private javax.swing.JButton jButton_eight;
    private javax.swing.JButton jButton_equal;
    private javax.swing.JButton jButton_five;
    private javax.swing.JButton jButton_four;
    private javax.swing.JButton jButton_minus;
    private javax.swing.JButton jButton_multiply;
    private javax.swing.JButton jButton_nine;
    private javax.swing.JButton jButton_one;
    private javax.swing.JButton jButton_plus;
    private javax.swing.JButton jButton_seven;
    private javax.swing.JButton jButton_six;
    private javax.swing.JButton jButton_three;
    private javax.swing.JButton jButton_two;
    private javax.swing.JButton jButton_zero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField_display;
    // End of variables declaration//GEN-END:variables
}
